# Based on: https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-vue-and-nuxt

name: Prod Deploy

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Tell the build which commit triggered the workflow
      LAST_COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm test
      - run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Deploy to external Github Pages repository.
          # See: https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-deploy-to-external-repository-external_repository
          #
          # Before the first time we need to set the Secret and the Deploy Key:
          #   1. Generate SSH keys with the command: ssh-keygen -t rsa -b 4096 -C "<youremail or comment>" 
          #      See: https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key
          #   2. In the Github Pages repo, set the public key as a Deploy Key with write access (Settings > Deploy Keys).
          #   3. In the current Action repo, set the private key as a secret named ACTIONS_DEPLOY_KEY (Settings > Secrets).
          deploy_key: ${{ secrets.PROD_DEPLOY_KEY }}
          external_repository: aniverse-moe/aniverse-moe.github.io
          publish_branch: master
          publish_dir: ./dist